pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'Fishing-Reimagined'

include 'fabric'
include 'neoforge'
